from sentence_transformers import SentenceTransformer
from pymilvus import connections, Collection
from dotenv import load_dotenv
import os
from llm_gemini_flash import query_gemini_llm

# Load environment variables from .env file
load_dotenv()

# Load the sentence transformer model
model = SentenceTransformer('sentence-transformers/all-MiniLM-L6-v2')

def semantic_search_and_answer(question, department, top_k=5):
    """
    Perform semantic search in Milvus for a given question in a specified department and 
    generate an answer using Gemini LLM.

    :param question: User's query
    :param department: Department name to search within
    :param top_k: Number of results to fetch
    :return: Answer generated by Gemini LLM or an error message
    """
    if not department:
        return "Department not specified. Please provide a valid department."

    # Connect to Milvus
    try:
        connections.connect(
            host=os.getenv("MILVUS_HOST"),
            port=os.getenv("MILVUS_PORT"),
            alias=os.getenv("MILVUS_ALIAS")
        )
    except Exception as e:
        return f"Error: Failed to connect to Milvus: {str(e)}"

    collection_name = f"{department.lower()}_collection"

    try:
        # Get collection
        collection = Collection(name=collection_name)
        collection.load()

        # Generate embedding for the question
        try:
            question_embedding = model.encode(question)
        except Exception as e:
            return f"Error generating embedding: {str(e)}"

        # Search parameters
        search_params = {"metric_type": "L2", "params": {"nprobe": 10}}

        # Perform search
        results = collection.search(
            data=[question_embedding.tolist()],
            anns_field="embedding",
            param=search_params,
            limit=top_k,
            output_fields=["content"]
        )

        if not results or not results[0]:
            return f"No relevant information found in {department} department."

        # Extract content from search results
        contexts = [str(hit.fields.get('content', '')) for hits in results for hit in hits if hit.fields.get('content', '').strip()]

        if not contexts:
            return f"No readable content found in {department} department documents."

        # Combine retrieved contexts
        combined_context = " ".join(contexts)

        # Generate an answer using Gemini LLM
        return query_gemini_llm(question, combined_context)

    except Exception as e:
        return f"Error in semantic search for {department} department: {str(e)}"
